<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Omicron.Core.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Omicron.Core.Generators.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Omicron.Core.Generators\Omicron.Core.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="DocSharp.Binary.Doc" Version="0.18.1" />
    <PackageReference Include="DocSharp.Binary.Ppt" Version="0.18.1" />
    <PackageReference Include="DocSharp.Binary.Xls" Version="0.18.1" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="MimeKit" Version="4.16.0" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
    <PackageReference Include="SharpCompress" Version="0.48.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Tomlyn" Version="2.3.2" />
    <PackageReference Include="VersOne.Epub" Version="3.3.6" />
  </ItemGroup>
</Project>
